CC=pgcc
CXX=pgc++
FC=pgfortran
LD=pgc++
CFLAGS=-fast -acc -ta=host
FFLAGS=-fast -acc -ta=host
CXXFLAGS=-fast -acc -ta=host
LDFLAGS=-fast -acc -ta=host
LDLIBS += -lboost_program_options
NVTXLIB := -I/home/e.romanchenko/NVTX/c/include/

all: exe run

exe: one_thread.o
	$(LD) $(LDFLAGS) $(LDLIBS) -o $@ $^ ${NVTXLIB} ${boot}

run: exe
	./exe --precision=0.000001 --size=4096 --iter=1000

.PHONY: clean
clean:
	-rm -f *.o *.mod core exe
.SUFFIXES: .c .cpp .F90 .o
.cpp.o:
	$(CXX) $(CXXFLAGS) -c -o $@ $< ${NVTXLIB} ${boot}
.c.o:
	$(CC) $(CFLAGS) -c -o $@ $< ${NVTXLIB} ${boot}
.F90.o:
	$(FC) $(FFLAGS) -c -o $@ $< ${NVTXLIB} ${boot} 
